### ISSUE TITLE
Error occured when use `cmp-dotenv`

### ISSUE THREAD

**Issue by tan-wei** [SergioRibera/cmp-dotenv#1] opened 2024-01-01 13:33 UTC
Just use `cmp-dotenv` with this a default configure will cause error:

Here is the configure part:
```lua
require("cmp").setup {
    sources = {
        { name = "dotenv" }
    }
}
```

And the error message:
```
Failed to source `/home/winterreise/.local/share/nvim/lazy/cmp-dotenv/after/plugin/cmp-dotenv.lua`

vim/_editor.lua:0: InsertEnter Autocommands for "*"..script nvim_exec2() called at InsertEnter Autocommands for "*":0../home/winterreise/.local/share/nvim/lazy/cmp-dotenv/after/plugin/cmp-dotenv.lua: Vim(source):E5113: Error while calling lua chunk: ...cal/share/nvim/lazy/cmp-dotenv/lua/cmp-dotenv/option.lua:26: attempt to index a nil value
stack traceback:
	...cal/share/nvim/lazy/cmp-dotenv/lua/cmp-dotenv/option.lua:26: in function 'get'
	...cal/share/nvim/lazy/cmp-dotenv/lua/cmp-dotenv/dotenv.lua:30: in function 'load'
	...l/share/nvim/lazy/cmp-dotenv/after/plugin/cmp-dotenv.lua:3: in main chunk
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:481: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480>
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480: in function 'source'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:439: in function 'source_runtime'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:410: in function 'packadd'
	...
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:337: in function '_load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:187: in function 'load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:338: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:337>
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:337: in function '_load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:187: in function 'load'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:83: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:72>

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**

```

**Comment by tan-wei** [comment] 2024-01-01 13:36
I use `cmp-dotenv` as the dependencies of `cmp`, so it is loaded before `cmp`. Is that the reason?

**Comment by SergioRibera** [comment] 2024-01-01 20:29
Ooooh, thank you very much for the detail of the problem, give me a moment and I'll review it, I'll let you know as soon as I have a new release

**Comment by SergioRibera** [comment] 2024-01-01 21:44
@tan-wei Perfect, I just uploaded some changes, you can try to update and let me know if it solved it please.

**Comment by tan-wei** [comment] 2024-01-02 00:14
Thanks very much. I can confirm it works now!

**Comment by SergioRibera** [comment] 2024-01-02 01:03
No problem, it's a pleasure for me, thank you very much for using my plugin :D

**Comment by tan-wei** [comment] 2024-01-02 01:38
Great plugin I'd love to say.
BTW, is Windows supported for `load_shell`? Althogh I seldon use ENV in Windows. Seems it depends on the imlementation of Neovim.

Update. I see the code:
```lua
if opts.load_shell then
    local env_vars = vim.fn.environ()
    for key, value in pairs(env_vars) do
      M.env_variables[key] = { value = value, docs = '**From Shell**' }
    end
  end
...
```
My guess is right.

**Comment by neuromaancer** [comment] 2024-01-06 15:48
I have the same problem:
```bash
   Error  16:39:34 notify.error lazy.nvim Failed to source `/Users/neuromaancer/.local/share/nvim/lazy/cmp-dotenv/after/plugin/cmp-dotenv.lua`

vim/_editor.lua:0: InsertEnter Autocommands for "*"..script nvim_exec2() called at InsertEnter Autocommands for "*":0../Users/neuromaancer/.local/share/nvim/lazy/cmp-dotenv/after/plugin/cmp-dotenv.lua: Vim(source):E5113: Error while calling lua chunk: vim/shared.lua:0: s: expected string, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/shared.lua: in function 'trim'
	...local/share/nvim/lazy/cmp-dotenv/lua/cmp-dotenv/load.lua:52: in function 'load_data_from_text'
	...local/share/nvim/lazy/cmp-dotenv/lua/cmp-dotenv/load.lua:35: in function 'load_data'
	...cal/share/nvim/lazy/cmp-dotenv/lua/cmp-dotenv/dotenv.lua:66: in function 'load'
	...l/share/nvim/lazy/cmp-dotenv/after/plugin/cmp-dotenv.lua:3: in main chunk
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:481: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480>
	[C]: in function 'xpcall'
	...
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:439: in function 'source_runtime'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:410: in function 'packadd'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:342: in function '_load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:187: in function 'load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:338: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:337>
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:337: in function '_load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:187: in function 'load'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:83: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:72>

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
```
I use cmp-dotenv as the dependencies of cmp too, and I use the newest version I am sure.

**Comment by SergioRibera** [comment] 2024-01-06 16:27
@tan-wei Sorry for replying so late, I had not received notification about your comment, indeed, it depends on the implementation of Neovim, I have not tried to load environment variables on Windows, so I can not assure you that it works correctly there. If in case you tried it and see any problem, please let me know, so I can correct it.

**Comment by SergioRibera** [comment] 2024-01-06 16:29
@neuromaancer It's a similar problem caused by something else, give me a moment, and I'll upload an update

**Comment by SergioRibera** [comment] 2024-01-06 16:50
@neuromaancer I have uploaded an update, you could check if the error persists, anyway I am checking in which other points can occur similar problems, at the moment the problem was due to the existence of variables declared without value

**Comment by SergioRibera** [comment] 2024-01-06 16:59
@tan-wei I'm looking at doing something like this, although checking the documentation and other posts, vim.environ() is cross-platform :0

```lua
    local env_vars = vim.tbl_deep_extend("keep", vim.fn.environ(), vim.env)
```

Let me know if you have any problems on windows or if you have any suggestions.

**Comment by neuromaancer** [comment] 2024-01-07 08:25
Thanks! Now works well for me.

**Comment by SergioRibera** [comment] 2024-01-07 08:57
> Thanks! Now works well for me.

Great, I hope you enjoy the plugin and please don't hesitate to open an issue or a PR in case it's necessary 😁

**Comment by tan-wei** [comment] 2024-01-08 00:50
> @tan-wei Sorry for replying so late, I had not received notification about your comment, indeed, it depends on the implementation of Neovim, I have not tried to load environment variables on Windows, so I can not assure you that it works correctly there. If in case you tried it and see any problem, please let me know, so I can correct it.

Yes, it depends on the implementation of Neovim. I think we should do nothing despite Neovim does not implement this on Windows. As we all known, Neovim on Windows is not awesome now.

**Comment by SergioRibera** [comment] 2024-01-08 06:41
Hahahaha, totally, very few people use neovim on Windows, well anyway `environ()` should work. I'm going to close the issue because apparently it's already solved.

**Closed as completed** 2024-01-08 06:41 UTC
